name: Generate APK

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK (fixed)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Your desired Java version
          distribution: 'adopt'  # Using AdoptOpenJDK (replace if needed)
